sudo: required
dist: trusty

language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python-dev python-apt python-pip ansible libffi-dev libssl-dev
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine


install:
  - sudo pip install urllib3
  - sudo pip install pytest
  - sudo pip install docker-py==1.7.1
  - sudo util/install.sh
  - sudo make develop
  - docker pull ubuntu:trusty

script:
  - sudo py.test -v mininet/test/test_containernet.py
